seed: 0
run_mode: 'finetune'
output_dir: './output' # path to save checkpoint/strategy
load_checkpoint: ''
src_strategy_path_or_dir: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
only_save_strategy: False
resume_training: False

# ==== context config ====
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: "--disable_expand_ops=Softmax,Dropout --enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  max_call_depth: 10000
  max_device_memory: "58GB"
  save_graphs: False
  save_graphs_path: "./graph"
  device_id: 0
  jit_config:
    jit_level: "O1"
  memory_optimize_level: "O0"

# aicc
remote_save_url: "Please input obs url on AICC platform."

# ==== model config ====
model:
  model_config:
    type: ChatGLM2Config
    batch_size: 1   # only for incremental infer
    num_layers: 40
    padded_vocab_size: 151552
    hidden_size: 4096
    ffn_hidden_size: 13696
    kv_channels: 128
    num_attention_heads: 32
    seq_length: 8192
    hidden_dropout: 0.0
    attention_dropout: 0.0
    layernorm_epsilon: 1.e-5
    rmsnorm: True
    apply_residual_connection_post_layernorm: False
    post_layer_norm: True
    add_bias_linear: False
    add_qkv_bias: True
    bias_dropout_fusion: True
    multi_query_attention: True
    multi_query_group_num: 2
    apply_query_key_layer_scaling: True
    attention_softmax_in_fp32: True
    fp32_residual_connection: False
    quantization_bit: 0
    pre_seq_len: None
    prefix_projection: False
    param_init_type: "float32"
    compute_dtype: "bfloat16"
    layernorm_compute_type: "float32"
    rotary_dtype: "float32"
    use_past: False
    use_flash_attention: True # when use FlashAttention, seq_length should be multiple of 16
    use_prompt_flash_attention: False
    use_incre_flash_attention: False
    eos_token_id: 151329
    pad_token_id: 151329
    repetition_penalty: 1.0
    max_decode_length: 256
    checkpoint_name_or_path: ''
    offset: 0.0
    top_k: 1
    top_p: 1
    do_sample: True
    # refactor param
    qkv_concat: False
    mlp_concat: False
    use_llama_rope: True
    alpha: 1.0  # coef for sft loss
    beta: 1.0   # temperature of dpo loss in logsigmoid function
  arch:
    type: Glm4DPO

trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'glm4_9b'
# if True do, evaluate during the training process. if false, do nothing.
# note that the task trainer should support _evaluate_in_training function.
do_eval: False
eval_step_interval: 500
eval_epoch_interval: -1

metric:
  type: PerplexityMetric

processor:
  return_tensors: ms
  tokenizer: &tokenizer
    type: ChatGLM4Tokenizer
    vocab_file: ""
    clean_up_tokenization_spaces: false
    do_lower_case: false
    eos_token: "<|endoftext|>"
    pad_token: "<|endoftext|>"
    model_max_length: 8000
    padding_side: "left"
    remove_space: false
    additional_special_tokens: ["<|endoftext|>", "[MASK]", "[gMASK]", "[sMASK]", "<sop>", "<eop>", "<|system|>",
                               "<|user|>", "<|assistant|>", "<|observation|>", "<|begin_of_image|>", "<|end_of_image|>",
                               "<|begin_of_video|>", "<|end_of_video|>"]
  type: GLMProcessor


# ==== dataset config ====
train_dataset: &train_dataset
  data_loader:
    type: MindDataset
    dataset_dir: ""
    shuffle: False
  input_columns: ["chosen_input_ids","chosen_labels","chosen_attention_mask", "chosen_loss_mask","chosen_ref_logps","rejected_input_ids", "rejected_labels", "rejected_attention_mask", "rejected_loss_mask", "rejected_ref_logps"]
  output_columns: ["chosen_input_ids", "chosen_labels", "chosen_loss_mask", "chosen_ref_logps",
                  "rejected_input_ids", "rejected_labels", "rejected_loss_mask", "rejected_ref_logps"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  repeat: 1
  numa_enable: False
  prefetch_size: 1

train_dataset_task:
  type: DPODataset
  dataset_config: *train_dataset

eval_dataset: &eval_dataset
  data_loader:
    type: ADGenDataLoader
    dataset_dir: ""
    shuffle: False
    phase: "eval"
    version: 2
    origin_columns: ["content", "summary"]
  tokenizer: *tokenizer
  max_source_length: 256
  max_target_length: 256
  ignore_pad_token_for_loss: True
  input_columns: ["input_ids", "labels"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 1
  repeat: 1
  numa_enable: False
  prefetch_size: 1
  seed: 0

eval_dataset_task:
  type: KeyWordGenDataset
  dataset_config: *eval_dataset

# ==== runner config ====
runner_config:
  epochs: 1
  batch_size: 1
  sink_mode: True
  sink_size: 1
  # gradient_accumulation_steps: 32

runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: DynamicLossScaleUpdateCell
    loss_scale_value: 4096
    scale_factor: 2
    scale_window: 1000
  use_clip_grad: True
  local_norm: True

# lr schedule
lr_schedule:
  type: CosineWithWarmUpLR
  learning_rate: 1.e-5
  warmup_ratio: 0.01
  total_steps: -1 # -1 means it will load the total steps of the dataset

# optimizer
optimizer:
  type: FP32StateAdamWeightDecay
  beta1: 0.9
  beta2: 0.95
  eps: 1.e-8
  weight_decay: 0.1
  learning_rate: 1.e-5
# lr_scale: False
# lr_scale_factor: 256

# parallel config
use_parallel: True
parallel:
  parallel_mode: 1 # 0-dataset, 1-semi, 2-auto, 3-hybrid
  gradients_mean: False
  loss_repeated_mean: True
  enable_alltoall: False
  full_batch: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: True  # optimizer shard
  # parallel_optimizer_config:
  #   gradient_accumulation_shard: False #True
  #   parallel_optimizer_threshold: 64
  #   optimizer_weight_shard_size: 8
  strategy_ckpt_config:
    save_file: "./ckpt_strategy.ckpt"
parallel_config:
  data_parallel: 4
  model_parallel: 2
  pipeline_stage: 1
  expert_parallel: 1
  micro_batch_num: 1
  vocab_emb_dp: False
  use_seq_parallel: True
  gradient_aggregation_group: 4
micro_batch_interleave_num: 1

# moe
moe_config:
  expert_num: 1
  capacity_factor: 1.05
  aux_loss_factor: 0.05
  num_experts_chosen: 1

# recompute
recompute_config:
  recompute: False
  select_recompute: [
    'mlp\.activation_func\.mul',
    'mlp\.activation_func\.silu\.silu',
    'mlp\.dense_left\.reshape',
    'mlp\.dense_4h_to_h\.reshape',
    'input_layernorm\.cast',
    'post_attention_layernorm\.cast',
  ]
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: False

# autotune
auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

# profile
profile: False
profile_start_step: 6
profile_stop_step: 10
init_start_profile: True
profile_communication: False
profile_memory: True

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: CheckpointMonitor
    prefix: "glm4-9b"
    save_checkpoint_steps: 5000
    keep_checkpoint_max: 1
    integrated_save: False
    async_save: False
  - type: ObsMonitor
    keep_last: False
eval_callbacks:
  - type: ObsMonitor
    keep_last: False
